### ISSUE TITLE
I'm facing this issue when generating token Could not find 'isRecaptchaLoaded' ('isRecaptchaLoaded' was undefined).

### ISSUE THREAD

**Issue by pjurkun** [hrryt/BlazoredRecaptcha#5]
code =>
 var token = await RecaptchaService.GenerateCaptchaTokenAsync("action");

Serice is getting injected into Blazor page.

when generating token got an error :

Could not find 'isRecaptchaLoaded' ('isRecaptchaLoaded' was undefined).
Error: Could not find 'isRecaptchaLoaded' ('isRecaptchaLoaded' was undefined).
    at https://localhost:7216/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:7216/_framework/blazor.server.js:1:465)
    at E (https://localhost:7216/_framework/blazor.server.js:1:2606)
    at https://localhost:7216/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:7216/_framework/blazor.server.js:1:3475)
    at https://localhost:7216/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:7216/_framework/blazor.server.js:1:71987)

Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=Could not find 'isRecaptchaLoaded' ('isRecaptchaLoaded' was undefined).
Error: Could not find 'isRecaptchaLoaded' ('isRecaptchaLoaded' was undefined).
    at https://localhost:7216/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:7216/_framework/blazor.server.js:1:465)
    at E (https://localhost:7216/_framework/blazor.server.js:1:2606)
    at https://localhost:7216/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:7216/_framework/blazor.server.js:1:3475)
    at https://localhost:7216/_framework/blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:7216/_framework/blazor.server.js:1:71987)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at BlazoredRecaptcha.RecaptchaService.<GenerateCaptchaTokenAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Portal.FrontendServer.Pages.RegistrationComponent.Register.<SaveRegistration>d__46.MoveNext() in C:\!WORK\SOFTORDER\ShootersPortal\ShootersPortal\Portal.FrontendServer\Pages\RegistrationComponent\Register.cs:line 72

  This exception was originally thrown at this call stack:
    [External Code]
    Portal.FrontendServer.Pages.RegistrationComponent.Register.SaveRegistration() in Register.cs

**Comment by hrryt** [comment]
Hey! Please ensure that you copied the blazoredRecaptcha.min.js files into your wwwroot directory and link them up with the necessary script tags on your layout page.

Currently, I am unsure on how to actually bundle the JS files in with the library.
